### ISSUE TITLE
Add Pixel Launcher module

### ISSUE THREAD

**Issue by miigotu** [topjohnwu/magisk-module-template#10]
Hi, not sure if there is a reason this module is not added to the repo yet, but if not could you add it please? I have been using it on my 6p for months and have no issues with it. Thanks.
https://github.com/jaimbo/PixelLauncher

**Comment by HUMORCE** [comment]
:) the right way here :
Open an issue in topjohnwu/Magisk_Repo_Central
https://github.com/topjohnwu/Magisk_Repo_Central/issues/new

**Comment by miigotu** [comment]
Thanks.
