### ISSUE TITLE
[Feature] Flash again to uninstall

### ISSUE THREAD

**Issue by Didgeridoohan** [topjohnwu/magisk-module-template#13]
RorschX1 has a nifty feature in his modules in the repo, AdaptiveSound and CrossBreederLite. You can flash the zip again to uninstall the module. Very handy in case of problems with the module. I'm not sure if his script handles updates, but the solution could work like this:

If the module is already installed and the same version as the one being flashed, uninstall the module.

**Comment by Zackptg5** [comment]
That's a pretty sweet idea. Added to unifiedhostsadblock in v2.7 update

**Comment by GeoZac** [comment]
@Zackptg5 can you make a pull request to add this to the module template?

**Comment by dark-1** [comment]
But the problem is , if you have to update your modules then you will have to flash it twice,
coz first it will uninstall then for second time it will install fresh.

**Comment by therealahrion** [comment]
No, because it has to be the same version to uninstall. If you have an update it will install the update.

**Comment by GeoZac** [comment]
May I suggest a check for version code too,then we we would be safe as Magisk manager keeps all downloaded modules and none to big in size.

**Comment by dark-1** [comment]
Let's also take this case of scenario where twrp didn't install the module Properly and wants to just reinstall or overwrite the previous install.
Then how will you tackle this.
Version check won't work in this case.

**Comment by therealahrion** [comment]
If it doesn't install properly that means the script is incorrect.

**Comment by dark-1** [comment]
> If it doesn't install properly that means the script is incorrect.

Doesn't have to be script , can be any environment problem or caused by any other script or by TWRP it's self or if TWRP is unstable for particular device ,,,, anything .....

**Comment by dark-1** [comment]
A matter of fact , Even I liked this feature but when I realized that it might cause PITA at later stage , decided not to say anything.
But when you guys wanted to get it to realization , then I just wanted to add my thought's to this Discussion.
Best Regards. 👍

**Comment by Zackptg5** [comment]
Got it perfected in this pull request: #41

**Comment by VR-25** [comment]
For situations when you need to reinstall the module, "touch /data/r" does the trick. I use that in two of my modules already.
Below is an example:

#----------------------------
# Migrate data and/or remove obsolete files ###
persist_dir=/data/media/$MODID
[ -f $ModPath/module.prop ] && CurVersionCode="`grep_prop versionCode $ModPath/module.prop`" \
	|| CurVersionCode=0

# Flash same version to uninstall ###
if [ ! -f /data/r ] && [ "`grep_prop versionCode $INSTALLER/module.prop`" -eq "$CurVersionCode" ]; then
  rm -rf $persist_dir $TMPDIR
  if $BOOTMODE; then
    touch $ModPath/remove
  else
    rm -rf $ModPath
    recovery_cleanup
  fi
  $BOOTMODE && exec echo -e "\n(i) Reboot to finish uninstall.\n" \
		|| exec ui_print "\n(i) Module uninstalled.\n"
fi

[ "$CurVersionCode" -lt '201712150' ] && rm -rf $persist_dir
mkdir -p $persist_dir/info 2>/dev/null
#----------------------------

$ModPath is always /data/magism.img's $MOUNTPATH/$MODID

**Comment by sjayminsgithub** [comment]
Magisk utility functions have "getvar" defined, user can edit reinstall=true in /cache/.magisk and we are good to go, why would we not use this internal programs ??? Magisk is the platform we are developing for !!!!!

**Comment by Didgeridoohan** [comment]
Is this thing still open? Nope... :)
