### ISSUE TITLE
Cant get acces to existing repo

### ISSUE THREAD

**Issue by yarpiin** [topjohnwu/magisk-module-template#23]
Hi,
I should have a acces to colaborate in existing repo but i dont. Can you have a look .
https://github.com/Magisk-Modules-Repo/magisk-UKM.git
repo on my git is up to date but need to push changes itno cloned in Magisk Repo

Regards

**Comment by topjohnwu** [comment]
https://github.com/Magisk-Modules-Repo/magisk-UKM/invitations
