### ISSUE TITLE
CRLF on windows

### ISSUE THREAD

**Issue by kudiaborm** [topjohnwu/magisk-module-template#3]
Looks like windows might be breaking my line endings
Did a diff and my local version was using CRLF

Pulling the file with git on windows automatically changed it and it seems difficult to change it back to just LF

https://help.github.com/articles/dealing-with-line-endings/

Shows how to force lf even on windows. Perhaps adding this info to the wiki? I'll add this as an issue on the module template as well

**Comment by therealahrion** [comment]
Is that what causes the  module to bot be recognized as a module or get an "installation error"?

**Comment by kudiaborm** [comment]
@therealahrion that is indeed one thing that would cause it on windows. In notepad++ you can change the line endings through `Edit > EOL Conversion`. In Android Studio, what I was using it's `File > Line Endings` with all files selected.

**Comment by therealahrion** [comment]
Ahh. Thank you. I'll try this.

**Comment by topjohnwu** [comment]
I added .gitattributes, so it shall force LR endings now
