### ISSUE TITLE
Magisk 14.0 Template

### ISSUE THREAD

**Issue by alukarulz** [topjohnwu/magisk-module-template#31]
Updated from 13.3 to 14.0 Magisk

updated my module to the new template.

When I flash modulefrom Magisk Manager or twrp  it tells me this
```
/data/magisk isn't setup properly!
Please install Magisk 14.0+
Failed
Installation error!
```

**Comment by xerta555** [comment]
> /data/magisk isn't setup properly!
Apparently u have to uninstall and install again propeply Magisk v14 via TWRP/CWM.
