### ISSUE TITLE
Only 1 .core script will run during boot

### ISSUE THREAD

**Issue by Zackptg5** [topjohnwu/magisk-module-template#38]
When multiple .core scripts are present (applies to both post-fs-data and service), only 1 of them will run. For my example, I made 3 scripts (test1.sh, test2.sh, and test3.sh) and placed them in each post-fs-data and service folders. Upon booting, only test2.sh ran in both cases. Attached is the magisk log. This issue has been present since magisk 14.0
[magisk_error_20171015_102646.log](https://github.com/topjohnwu/magisk-module-template/files/1385516/magisk_error_20171015_102646.log)

**Comment by MichaelHu55** [comment]
me too, my device is oneplus 3t, magisk 14.3

**Comment by MichaelHu55** [comment]
i have the same issue.
