### ISSUE TITLE
Don't rename zip when flashing in magisk manager

### ISSUE THREAD

**Issue by Zackptg5** [topjohnwu/magisk-module-template#40]
A common method of triggering an action in a zip is to change the zip name. Magisk Manager changes the zipname to "install" which breaks this feature

Also, if it could not be copied to a temp directory and instead be extracted to a temp directory, that would also be beneficial as another nice feature for more dynamic zips is to use the zip path as a directory for other files

**Comment by topjohnwu** [comment]
@Zackptg5 this is a limitation of Android's file selection. You can select a file from Google Drive and Magisk will have to treat it the same, and that file will not have a location.
