### ISSUE TITLE
Huawei p9 lite problem

### ISSUE THREAD

**Issue by Loreri** [topjohnwu/magisk-module-template#46]
I have a huawei p9 lite with Revolution Remix redone from meticulus: 
http://www.meticulus.co.vu/p/ressurection-remix-for-hi6250-devices.html

And with version 15, 15.1, 15.2 the celular enters a boot loop while with the 14. (I do not remember) everything went perfectly. Download the files from the official site because I can not release for a copyright burn.

Sorry for the english but I translated it with google translator.

**Comment by Meticulus** [comment]
@Loreri Please remove links to my files please.

**Comment by Meticulus** [comment]
I fix this, you can close issue. :thinking: :joy: :+1:
