### ISSUE TITLE
bug with magisk template 1500 but not 1400

### ISSUE THREAD

**Issue by ITDante93** [topjohnwu/magisk-module-template#50]
Dear topjohnwu, 
I hope this finds you well... 
I make soundmods,
on Vanilla 1400 template replace and set_perm for mixer_gains.xml is working but template 1500 the phone gets stuck at bootanimation... 
Is there a workaround this bug...? 
Thank you very much in advance...

**Comment by ITDante93** [comment]
I can provide a sample of my work to be tested if that helps...

**Comment by topjohnwu** [comment]
I believe this is nothing wrong with the template itself.
It is either a Magisk bug, or you are configuring it incorrectly.
