### ISSUE TITLE
Add Free Software License

### ISSUE THREAD

**Issue by Scrumplex** [topjohnwu/magisk-module-template#51]
This project does not have a license at the moment. This means, that all rights are reserved to @topjohnwu. A license (like the GPL-3.0 or Apache-2.0) could solve this issue, by giving everyone a typical free-software license.

**Comment by dark-1** [comment]
This is a Template ,
If you are developing a module the you have to add it your self , while publishing it to Magisk repo.

Best Regards. 👍

**Comment by Scrumplex** [comment]
Technically, forking is not even permitted, as topjohnwu has ALL the rights to this template. He needs to declare usage rights in order to allow modifications.

**Comment by dark-1** [comment]
Well !!! there are currently 324 forks at this movement.   
+   
this is GitHub,   
& you are Here,   
So you may want to read this CareFully : [D. User-Generated Content](https://help.github.com/articles/github-terms-of-service/#d-user-generated-content)   

Best Regards. 👍

**Comment by Scrumplex** [comment]
Closing this now,

**Comment by sjayminsgithub** [comment]
Also, if you added GPL v3.0, then the developer will be forced to release their closed source binaries' source code, and also to document their source code. And if used Apache 2.0, the developer will be forced to document their source code. Why would you think that is reasonable ??

**Comment by Scrumplex** [comment]
I thought more of the WTFPL
