### ISSUE TITLE
Remove all comments for reducing size

### ISSUE THREAD

**Issue by megapro17** [topjohnwu/magisk-module-template#52]
How can I carefully do that? I tried, but then it won't install.

**Comment by ShadySquirrel** [comment]
Why would you remove comments? Contents are text, whole module template isn't even 100KB, you won't gain anything with that.

**Comment by dark-1** [comment]
@megapro17 ,  
   
If you see start of file with `#!/` , do not remove that line , keep as is, all other comment line can be removed.    
Also may be `#MAGISK` , leave it as is.   

BTW i go with @ShadySquirrel  as it's in significant in terms of disk space, But if you mean `reducing size` by no of lines per file then it's fine.   

Best regards. 👍
