### ISSUE TITLE
! /data/adb/magisk_merge.img mount failed

### ISSUE THREAD

**Issue by mastersheea** [topjohnwu/magisk-module-template#56]
Hello to everyone!
Doogee Mix 2, error install magisk modules.
No possible to install any module.
! /data/adb/magisk_merge.img mount failed...
I have tried: ln -s /sbin/magisk /sbin/.core/mirror/bin/magisk, to flash f2fs-loopback-bug-workaround, to reinstall magisk, to reinstall Boot partition, to flash via TWRP, to flash via flashify.
Nothing works.
Someone helps, please?
Thank you in advance :)

**Comment by sjayminsgithub** [comment]
Hello @mastersheea, this issue doesn't belong here.
If it's a Magisk bug, head over to the Magisk repo, this is just a template for installing modules.
Kindly close this issue.

**Comment by dark-1** [comment]
>Hello @mastersheea, this issue doesn't belong here.
If it's a Magisk bug, head over to the Magisk repo, this is just a template for installing modules.
Kindly close this issue.
   
Well!!!! I can see you are on "magisk-module-template" cleaning spree.    
Good Luck. 👍     
    
Best regards. 😄

**Comment by sjayminsgithub** [comment]
@dark-1,
Thanks, Since @topjohnwu has moved all the code into util_functions.sh, I was working on to develop my own template, so I checked through this Repo and found out these unwanted issues/PRs.
Then I thought I would do something to help topjohnwu while he is away.
