### ISSUE TITLE
cant give me a practice to make magisk module

### ISSUE THREAD

**Issue by JejeNop** [topjohnwu/magisk-module-template#59]
a

**Comment by sjayminsgithub** [comment]
What is this issue for ??

**Comment by dark-1** [comment]
> What is this issue for ??   
   
A Spam , Apparently.

**Comment by sjayminsgithub** [comment]
@JejeNop,
Could you describe your issue, or as @dark-1 said, were you trying to practice how to create issues at GitHub at this Repo ??

**Comment by JejeNop** [comment]
i want to learn, like make a magisk modul, dunno what to do

Pada tanggal Sel, 24 Apr 2018 00.07, Jaymin Suthar <notifications@github.com>
menulis:

**Comment by dark-1** [comment]
@JejeNop ,    
> i want to learn, like make a magisk modul, dunno what to do   
    
Now we can help you.   
Here : [Magisk Module official documentations](https://github.com/topjohnwu/Magisk/blob/master/docs/modules.md) .    

And close this Issue.
As nothing wrong in this module.

Best regards. 👍

**Comment by sjayminsgithub** [comment]
@JejeNop,

A magisk module can be better understood as a structure of some specified files put in an order inside the magisk.img image.

The structure can be found in the link @dark-1 gave you. You can write your own flashables if you want, or simply use this template, it's upto you.

Kindly close this issue now, And if you need any further help, create a Q/A thread at xda-developers.

Jaymin Suthar

**Comment by sjayminsgithub** [comment]
@JejeNop, could you kindly close this issue??

**Comment by dark-1** [comment]
> @JejeNop, could you kindly close this issue??
    
@sjayminsgithub , don't worry , @topjohnwu  will do that soon.
