### ISSUE TITLE
"Is not a Magisk Module"

### ISSUE THREAD

**Issue by psy0ch** [topjohnwu/magisk-module-template#64]
I have used the Template provided to make my own Module that replaces the standart Bootanim.
If I try to add it through the Manager I just get the error: "Is not a Magisk Module"

I used the up to date Template, made sure to copy the updater-script and edited all the files according to information provided. The files were edited using Notepad++, so it should be fine.

Link to my Module:
https://cdn.discordapp.com/attachments/81885715062853632/484468718873870338/Valor.rar

**Comment by dark-1** [comment]
>Link to my Module:   
>https://cdn.discordapp.com/attachments/81885715062853632/484468718873870338/Valor.rar   

It should be a `.zip` File & not `.rar` file.   

Best regards 👍
