### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by gloeyisk** [topjohnwu/magisk-module-template#75]
Hello.
Is it possible to make Canary Template? Thanks.

**Comment by Didgeridoohan** [comment]
Why would you need that? The current module template works perfectly for the current stable and canary releases. Until the /sbin/.core symlink is deprecated or there is some other change in Magisk that calls for it, there's really no need for an update.

If you feel that you need to make a module that is aimed at a particular Magisk release, you can always make a check with the `magisk -V` command to see which version of Magisk is running.
