### ISSUE TITLE
Empty author and description

### ISSUE THREAD

**Issue by MarcAnt01** [topjohnwu/magisk-module-template#76]
I am unable to edit this fields and even if they are OK in module.prop they are not being shown in Magisk Manager, I can forward required files here if needed

**Comment by Didgeridoohan** [comment]
This is not the place for help with module creation. I would take it to xda...

Having said that, I'm gonna guess you're not using an integer in versionCode. You should probably read the docs: https://topjohnwu.github.io/Magisk/guides.html#magisk-modules

You should close this issue now.

**Comment by MarcAnt01** [comment]
I have tried twice with the template, but still the same problem, I don't know if it is a problem of mine or a template bug as I have done the procedure properly

**Comment by MarcAnt01** [comment]
Managed to fix, thx a lot for your help @Didgeridoohan
